oharastream/ohara

README.md
=> OHARA-1420 Update README.md

README.md
=> #390 Add your name in the Authors section of README.md

README.md, ohara-manager/README.md
=> #438 Improve Ohara README.md and Manager README.md

ohara-manager/client/cypress/integration/brokerPage.test.js, ohara-manager/client/cypress/support/commands.js, ohara-manager/client/src/components/pages/Services/TopicNewModal/TopicNewModal.js, ohara-manager/client/src/constants/urls.js
=> #680 Cypress e2e test broker with service page

ohara-manager/client/src/components/pages/Services/BrokerListPage/BrokerListPage.js, ohara-manager/client/src/components/pages/Services/ZookeeperListPage/ZookeeperListPage.js, ohara-manager/client/src/components/pages/Services/ZookeeperListPage/styles.js, ohara-manager/client/src/components/pages/Services/styles.js
=> #738 ZK & BK service info display is incomplete

ohara-manager/client/cypress/integration/brokerPage.test.js, ohara-manager/client/cypress/integration/zookeeperPage.test.js
=>  #772 Cypress e2e test broker and zookeeper with service page

ohara-kafka/src/main/java/com/island/ohara/kafka/connector/RowSinkContext.java
=> #814 RowSinkContext.offset should take primitive type.

ohara-manager/client/cypress/integration/pipelineNewPage.test.js
=> #752 Add e2e tests to verify that users can see the correct relation between connectors in the pipeline graph

ohara-configurator/src/main/scala/com/island/ohara/configurator/store/DataStore.scala, ohara-configurator/src/test/scala/com/island/ohara/configurator/TestConfiguratorStore.scala, ohara-configurator/src/test/scala/com/island/ohara/configurator/store/TestDataStore.scala
=> #864 DataStore#exist() should return false if id not exist

ohara-manager/.gitignore, ohara-manager/build.gradle, ohara-manager/package.json, ohara-manager/scripts/cleanAllServices.js, ohara-manager/scripts/createServices.js, ohara-manager/scripts/env/service.json, ohara-manager/utils/apiHandler.js
=>  #759 Add a final like hook in frontend e2e tests

ohara-manager/client/src/components/pages/Services/BrokerListPage/BrokerListPage.js, ohara-manager/client/src/components/pages/Services/ZookeeperListPage/ZookeeperListPage.js
=> #926 Manager fails to render zookeeper and broker pages

.gitignore, ohara-manager/build.gradle, ohara-manager/client/cypress/support/commands.js, ohara-manager/scripts/cleanAllServices.js, ohara-manager/scripts/createServices.js, ohara-manager/scripts/startAndTest.js, ohara-manager/utils/apiHandler.js
=> #874 Start and clean services for running all frontend e2e tests

ohara-manager/client/cypress.json, ohara-manager/client/cypress/integration/pipelineNewPage.test.js
=> #895 Fix brokers, pipeline List page and workers pages flaky tests

docs/rest_interface.md
Fix example request under upload jar section.
=> #1016 [docs] adding jar section example keyword should be "jar" but "filename" 

ohara-manager/client/cypress/integration/pipelineNewPage.test.js
=> #1012 Fix frontend pipeline new/edit page flaky e2e tests

docs/rest_interface.md
examples in validate nodes should be hostname but name
=> #1066 [docs] readme on validation node connection has wrong example request

ohara-manager/client/cypress/integration/brokerPage.test.js, ohara-manager/client/cypress/integration/workerPage.test.js, ohara-manager/client/src/api/topicApi.js, ohara-manager/client/src/api/workerApi.js, ohara-manager/client/src/components/pages/Services/TopicNewModal/TopicNewModal.js, ohara-manager/client/src/components/pages/Services/WorkerListPage/WorkerListPage.js, ohara-manager/client/src/components/pages/Services/WorkerNewModal/WorkerNewModal.js, ohara-manager/client/src/components/pages/Services/__tests__/WorkerListPage.test.js, ohara-manager/client/src/components/pages/Services/__tests__/WorkerNewModal.test.js
=>  #1052 As a Frontend dev, we should stabilize flaky end-to-end tests

ohara-manager/client/cypress/integration/brokerPage.test.js, ohara-manager/client/cypress/integration/pipelineNewPage.test.js, ohara-manager/client/cypress/integration/streamApp.test.js, ohara-manager/client/cypress/integration/workerPage.test.js, ohara-manager/client/cypress/support/commands.js, ohara-manager/client/cypress/utils.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineListPage.js, ohara-manager/client/src/components/pages/PipelinePage/__tests__/PipelineListPage.test.js, ohara-manager/scripts/handleServices.js, ohara-manager/scripts/startAndTest.js
=> #1179 Fix frontend flaky e2e tests

ohara-manager/client/src/api/__tests__/topicApi.test.js, ohara-manager/client/src/api/__tests__/workerApi.test.js, ohara-manager/client/src/api/topicApi.js, ohara-manager/client/src/api/workerApi.js
=> #1216 Multiple zookeepers and multiple brokers cause topic can't create

ohara-manager/client/cypress/integration/pipelineNewPage.test.js, ohara-manager/client/cypress/support/commands.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/CustomConnector/UtilsTabs.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/CustomConnector/__tests__/customConnectorUtils.test.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/CustomConnector/customConnectorUtils.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/FtpSource.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/__tests__/JdbcSource.test.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/styles.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineNewPage/PipelineNewPage.js
=> #1168 Rewrite ftp source connector component and use the new API

ohara-manager/client/src/components/common/Form/Input.js, ohara-manager/client/src/components/common/FormFields/InputField.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/CustomConnector/CustomFinalForm.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/CustomConnector/customConnectorUtils.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/FtpSource.js
=> #1168 Wrap ftp source connector with final form

ohara-manager/client/src/components/pages/PipelinePage/Connectors/CustomConnector/ColumnTable/ColumnTable.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/CustomConnector/ColumnTable/NewRowModal.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/CustomConnector/CustomFinalForm.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/CustomConnector/customConnectorUtils.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/FtpSource.js
=> #1168 Wrap ftp source connector metadata table type with final form

ohara-manager/client/src/components/pages/PipelinePage/Connectors/CustomConnector/CustomFinalForm.js
=> #1307 Metadata table sort fail

ohara-manager/client/cypress/integration/streamApp.test.js, ohara-manager/client/cypress/integration/zookeeperPage.test.js, ohara-manager/client/cypress/support/commands.js, ohara-manager/client/package.json, ohara-manager/client/yarn.lock
=> #1179 Upgrade Cypress to 3.3.0 and fix some streamApp e2e test bug

docker/deps.dockerfile
=> #1332 Install required cypress dependencies in docker image

docker/deps.dockerfile
=> #1332 Install required cypress dependencies (libgtk-3) in docker image

ohara-manager/client/cypress/integration/homepage.test.js, ohara-manager/client/cypress/integration/pipelineNewPage.test.js, ohara-manager/client/cypress/integration/workerPage.test.js, ohara-manager/client/cypress/support/index.js, ohara-manager/client/package.json, ohara-manager/client/src/components/pages/PipelinePage/Connectors/FtpSink.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/FtpSource.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/HdfsSink.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/JdbcSource.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineToolbar/PipelineNewConnector.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineToolbar/PipelineToolbar.js, ohara-manager/client/src/components/pages/PipelinePage/pipelineUtils/pipelineToolbarUtils.js, ohara-manager/client/yarn.lock
=> #1354 Fix pipeline new page and worker page e2e test fails

ohara-manager/client/cypress/integration/pipelineNewPage.test.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/FtpSink.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/FtpSource.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/HdfsSink.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/JdbcSource.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineToolbar/PipelineNewConnector.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineToolbar/PipelineToolbar.js, ohara-manager/client/src/components/pages/PipelinePage/pipelineUtils/__tests__/pipelineToolbarUtils.test.js, ohara-manager/client/src/components/pages/PipelinePage/pipelineUtils/pipelineToolbarUtils.js, ohara-manager/client/src/propTypes/pipeline.js
=>  #1462 Cannot create a new connector due to connector API changes

ohara-manager/build.gradle, ohara-manager/scripts/handleE2eServices.js, ohara-manager/scripts/runApiTests.js, ohara-manager/scripts/runE2eTests.js, ohara-manager/utils/configHelpers.js
=> #1492 Change test manager-api gradle keys

ohara-manager/client/cypress/api/api.test.js
=> #1490 Test manager-api in jenkins

ohara-manager/client/src/components/pages/PipelinePage/Connectors/connectorUtils.js
=>  #1472 HDFSSinkConnector some fields are not displayed

ohara-manager/client/public/index.html, ohara-manager/client/src/App.js
=> #1445 Do not remove jss inject point comment from the html in ohara manager's build step

ohara-manager/client/src/components/common/Mui/Table/SortTable.js, ohara-manager/client/src/components/common/Mui/Table/index.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesListPage/WorkspacesListPage.js
=> #1469 Add sorting function in table component

ohara-manager/client/src/components/pages/PipelinePage/Connectors/connectorUtils.js
=> #1524 Source connector cannot test config in UI

ohara-manager/client/src/components/common/Mui/Form/Button.js, ohara-manager/client/src/components/common/Mui/Table/SortTable.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/StreamApp/StreamApp.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/StreamApp/index.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/StreamApp/styles.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Tabs.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesListPage/WorkspacesListPage.js
=> #1469 Implement stream apps page

ohara-manager/client/src/api/brokerApi.js, ohara-manager/client/src/api/workerApi.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Nodes/Nodes.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Nodes/index.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Nodes/styles.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Tabs.js
=> #1469 Implement nodes page

ohara-manager/client/cypress/integration/workspacesPage.test.js, ohara-manager/client/src/api/brokerApi.js, ohara-manager/client/src/api/workerApi.js, ohara-manager/client/src/components/common/FormFields/InputField.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewConnectors.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/StreamApp/StreamApp.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/Topics.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesListPage/WorkspacesListPage.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js
=> #1538 Add topic page end-to-end tests

ohara-kafka/src/main/java/com/island/ohara/kafka/Producer.java
=> #1549 The default acks of Producer should be 1 than zero

ohara-manager/client/cypress/integration/workspacesPage.test.js, ohara-manager/client/cypress/support/commands.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/Topics.js
=> #1625 Fix manager IT failed tests

ohara-manager/client/cypress/integration/workspacesPage.test.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineToolbar/PipelineNewStream.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewStreamApps.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/StreamApp/StreamApp.js
=> #1646 Add file size in streamApp page

ohara-manager/client/src/components/pages/PipelinePage/PipelineToolbar/PipelineNewStream.js, ohara-manager/client/src/components/pages/WorkspacesPage/PluginSelectModal/PluginSelectModal.js
=> #1663 Fix pipeline streamApp modal can add space list

ohara-manager/scripts/handleE2eServices.js
=> #1666 Fix create e2e services wait containers failed

ohara-manager/client/src/components/common/Mui/Table/SortTable.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Nodes/Nodes.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/StreamApp/StreamApp.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/Topics.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Topics.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesListPage/WorkspacesListPage.js
=> #1628  Refactor sort table component making it more reusable

ohara-client/src/main/scala/com/island/ohara/client/configurator/v0/ConnectorApi.scala
=> #1656 Replace JsArray() by JsArray.empty 

ohara-manager/client/cypress/integration/workspacesPage.test.js, ohara-manager/client/cypress/support/commands.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewConnectors.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewNodes.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewStreamApps.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewTopics.js
=> #1628 Add more end-to-end tests 

ohara-manager/client/src/components/common/Mui/Form/InputField.js, ohara-manager/client/src/components/common/Mui/Form/Tooltip.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/connectorUtils.js
=> #1759 Missing port error when verifying Ftp source connector config

ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js
=> #1702 Create new workspace modal thrown an error after successfully created the workspace (backport to 0.6)

ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js
=> #1702 Create new workspace modal thrown an error after successfully created the workspace

ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Nodes/Nodes.js
=> #1776 Cannot deploy broker when add a new node into workspace (backport to 0.6)

ohara-manager/client/src/api/brokerApi.js, ohara-manager/client/src/api/workerApi.js, ohara-manager/client/src/api/zookeeperApi.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js
=> #1700 Abandon all the services if an error occurs while creating a workspace

ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Nodes/Nodes.js
=>  #1776 Cannot deploy broker when add a new node into workspace

ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Nodes/Nodes.js
=> #1776 Cannot deploy broker when add a new node into workspace

ohara-kafka/src/main/java/com/island/ohara/kafka/connector/json/SettingDefinition.java, ohara-kafka/src/test/java/com/island/ohara/kafka/connector/json/TestCoreDefinitions.java, ohara-manager/client/src/components/pages/PipelinePage/Connectors/connectorUtils.js
=> #1369 Change connector definition's prop from list to array

ohara-manager/client/src/components/common/Mui/Dialog/Dialog.js, ohara-manager/client/src/components/common/Mui/Feedback/Progress.js, ohara-manager/client/src/components/common/Mui/Feedback/index.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js
=> #1856 Add a loading progress bar to better inform users about the progress of a certain action

ohara-manager/client/cypress/e2e/workspacesPage.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewNodes.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/StreamApp/StreamApp.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesPage.js
=> #2043 Fix create workspace failed issue

ohara-manager/client/src/components/pages/NodePage/NodeEditModal.js, ohara-manager/client/src/components/pages/NodePage/__tests__/NodeListPage.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Nodes.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Overview.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/StreamApp.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Topics.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/__tests__/WorkspacesPage.test.js, ohara-manager/client/src/utils/generate.js
=> #1730 Update unit test with new api and snackbar

ohara-manager/client/src/components/controller/index.js, ohara-manager/client/src/components/controller/useGetApi.js, ohara-manager/client/src/components/controller/usePutApi.js, ohara-manager/client/src/components/controller/useValidationApi.js, ohara-manager/client/src/components/controller/useWaitApi.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/useCreateServices.js
=> #2046 Refactor manager's new workspace modal

ohara-manager/client/src/components/pages/WorkspacesPage/__tests__/WorkspacesPage.test.js
=> #2085 Fix unit test with workerspace page

ohara-manager/client/cypress/api/workerApi.js, ohara-manager/client/cypress/support/apiTest.js, ohara-manager/client/src/api/__tests__/jarApi.test.js, ohara-manager/client/src/api/jarApi.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js
=> #2088 Change worker api properties jars to jarKeys with manager

ohara-manager/client/src/components/common/Mui/Dialog/Dialog.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/TopicNewModal.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/Topics.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Topics.test.js
=> #1730 Refactor new topic modal with a better form validation feedback

ohara-manager/client/cypress/api/topicApi.js, ohara-manager/client/cypress/support/apiTest.js, ohara-manager/client/src/api/topicApi.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/TopicNewModal.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/Topics.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Topics.test.js
=> #1972 Apply "start" and "stop" action to Topic API with Ohara Manager

ohara-manager/client/src/components/pages/NodePage/NodeEditModal.js, ohara-manager/client/src/components/pages/NodePage/NodeListPage.js, ohara-manager/client/src/components/pages/NodePage/NodeNewModal.js, ohara-manager/client/src/components/pages/NodePage/__tests__/NodeListPage.test.js, ohara-manager/client/src/components/pages/NodePage/styles.js
=> #1730 Refactor node page so it's consistent with others Mui components

ohara-manager/client/src/components/pages/PipelinePage/Connectors/PerfSource.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/index.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineNewPage/SidebarRoutes.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/TopicNewModal.js, ohara-manager/client/src/constants/pipelines.js
=> #271 Implement perf source connector property form

ohara-manager/client/src/components/common/Header/__tests__/Header.test.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineToolbar/__tests__/PipelineToolbar.test.js, ohara-manager/client/src/components/pages/PipelinePage/__tests__/pipelineNewPage.test.js, ohara-manager/client/src/utils/testUtils.js
=> #2137 Clean up manager's test utility

ohara-manager/client/cypress/api/pipelineApi.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineListPage.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineNewPage/PipelineNewPage.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineNewPage/__tests__/pipelineNewPageUtils.test.js, ohara-manager/client/src/components/pages/PipelinePage/__tests__/pipelineNewPage.test.js
=> #1897 Remove "workerClusterName" from Pipeline with manager

ohara-agent/src/main/scala/com/island/ohara/agent/StreamCollie.scala, ohara-agent/src/main/scala/com/island/ohara/agent/k8s/K8SStreamCollieImpl.scala, ohara-agent/src/main/scala/com/island/ohara/agent/ssh/StreamCollieImpl.scala, ohara-agent/src/test/scala/com/island/ohara/agent/TestStreamCreator.scala, ohara-configurator/src/main/scala/com/island/ohara/configurator/fake/FakeStreamCollie.scala, ohara-configurator/src/main/scala/com/island/ohara/configurator/route/StreamRoute.scala
=> #2231 use URI constructor instead of URL for parsing url to server

docker/backend.yml, docker/build.yml, gradle.properties, ohara-manager/client/cypress/api/connectorApi.js, ohara-manager/client/cypress/api/validateApi.js
=> #2255 Update version of master branch to 0.8.0-SNAPSHOT

ohara-configurator/src/main/scala/com/island/ohara/configurator/route/WorkerRoute.scala, ohara-it/src/test/resources/log4j.properties
=> #2251 Worker should update the fetch connector list (backport to 0.7)

ohara-manager/client/cypress.json, ohara-manager/client/cypress/e2e/pipelineNewPage.test.js, ohara-manager/client/cypress/e2e/workspacesPage.test.js, ohara-manager/client/cypress/support/e2eCommands.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineGraph/pipelineGraphUtils.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineNewPage/Metrics/MetricsListItem.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineNewPage/Metrics/TopicMetrics.js
=> #2189 Add more e2e test with perf connector and metrics

ohara-manager/client/cypress/e2e/workspacesPage.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewStreamApps.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Tabs.js
=> #2325 Rename Stream Apps to Stream Jar with workspaces page

ohara-manager/client/src/components/pages/PipelinePage/Connectors/ConsoleSink.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/index.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineNewPage/SidebarRoutes.js, ohara-manager/client/src/constants/pipelines.js
=> #2250 Implement console sink connector with manager

ohara-kafka/src/main/java/com/island/ohara/kafka/Producer.java
@chia7712 can u take a look ? Since this is just a doc fix, I didn't attach any test.
=> #2342 Correct the comment of Producer.Builder.noAcks

docker/backend.yml, docker/build.yml, gradle.properties, ohara-manager/client/cypress/api/connectorApi.js, ohara-manager/client/cypress/api/validateApi.js
=> #2419 Update version of 0.7 branch to 0.7.0

docker/backend.yml, docker/build.yml, gradle.properties, ohara-manager/client/cypress/api/connectorApi.js, ohara-manager/client/cypress/api/validateApi.js
=> #2434 Update version of 0.7 branch to 0.7.1-SNAPSHOT

ohara-manager/client/cypress/api/brokerApi.js, ohara-manager/client/cypress/api/workerApi.js, ohara-manager/client/cypress/api/zookeeperApi.js, ohara-manager/client/cypress/e2e/workspacesPage.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/Overview.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewNodes.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/styles.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Overview.test.js
=> #2297 Show all used images in workspace overview page's basic info section

ohara-manager/client/cypress/e2e/workspacesPage.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/Overview.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewPlugin.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewStreamApps.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewTopics.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Plugins/Plugins.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Plugins/styles.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/StreamApp/StreamApp.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Tabs.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/TopicNewModal.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/Topics.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js
=> #2482 Add plugins tab in workspace and inside overview tab

ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewConnectors.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewNodes.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Overview.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Topics.test.js, ohara-manager/client/src/utils/generate.js
=> #2183 Add workspace overview unit tests

ohara-agent/src/main/scala/com/island/ohara/agent/BrokerCollie.scala
=> #2243 redefine the nodeNames and deadNodes for Broker cluster

docker/backend.yml, docker/build.yml, gradle.properties, ohara-manager/client/cypress/api/connectorApi.js, ohara-manager/client/cypress/api/validateApi.js
=> #2578 Update version of 0.7 branch to 0.7.1

docker/backend.yml, docker/build.yml, gradle.properties, ohara-manager/client/cypress/api/connectorApi.js, ohara-manager/client/cypress/api/validateApi.js
=> #2580 Update version of 0.7 branch to 0.7.2-SNAPSHOT

ohara-manager/client/src/components/common/Mui/Feedback/Progress.js, ohara-manager/client/src/components/common/Mui/Table/SortTable.js, ohara-manager/client/src/components/common/Mui/Table/TableToolbar.js, ohara-manager/client/src/components/controller/useFetchApi.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Plugins/Plugins.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Tabs.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/WorkspacesDetailPage.js, ohara-manager/client/src/theme/muiTheme.js
=> #2483 Upgrade workspace with updated plugins

ohara-manager/client/src/components/common/Mui/Feedback/Progress.js, ohara-manager/client/src/components/common/Mui/Table/TableToolbar.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Plugins/Plugins.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Plugins/usePlugin.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/StreamApp/StreamApp.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/Topics.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/StreamApp.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Topics.test.js, ohara-manager/client/src/theme/muiTheme.js, ohara-manager/client/src/utils/generate.js
=> #2484 Restore workspace if the upgrade failed

ohara-manager/client/cypress/e2e/workspacesPage.test.js, ohara-manager/client/cypress/support/e2eCommands.js, ohara-manager/client/src/components/common/Mui/Dialog/DeleteDialog.js, ohara-manager/client/src/components/common/Mui/Form/InputField.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Plugins/Plugins.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Plugins/usePlugin.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Plugins.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/validate.js, ohara-manager/scripts/handleE2eServices.js, ohara-manager/scripts/runE2eTests.js
=> #2622 Add e2e and unit tests with plugins

ohara-manager/client/src/components/pages/PipelinePage/Connectors/Connector.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/Tabs.js, ohara-manager/client/src/components/pages/PipelinePage/Connectors/connectorUtils.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineEditPage/PipelineEditPage.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineGraph/PipelineGraph.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineGraph/pipelineGraphUtils.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js
=> #2547 Ohara manager support JsonIn and JsonOut

ohara-manager/client/cypress/api/brokerApi.test.js, ohara-manager/client/cypress/api/workerApi.test.js, ohara-manager/client/cypress/api/zookeeperApi.test.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineEditPage/PipelineEditPage.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineListPage/PipelineListPage.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Node/Nodes.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/Overview.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewNodes.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Overview/OverviewTopics.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Plugins/Plugins.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Plugins/usePlugin.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Nodes.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Overview.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/__tests__/Plugins.test.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesPage.js, ohara-manager/client/src/components/pages/WorkspacesPage/__tests__/WorkspacesPage.test.js, ohara-manager/client/src/utils/generate.js
=> #2438 Ohara Manager should fetch the object data from settings

ohara-client/src/main/scala/com/island/ohara/client/configurator/v0/StreamApi.scala, ohara-client/src/test/scala/com/island/ohara/client/configurator/v0/TestStreamApi.scala
=> #2438 remove stale fields for StreamClusterInfo

ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/useCreateServices.js
=>  #2757 Increase waiting time for workspace creation

ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Plugins/Plugins.js
=> #2762 Updating plugins sometimes results in abnormal display and errors

ohara-manager/client/cypress/support/e2eCommands.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/useCreateServices.js, ohara-manager/scripts/handleE2eServices.js
=> #2781 Failure to establish workspace correctly

ohara-manager/client/cypress/api/connectorApi.test.js, ohara-manager/client/cypress/e2e/workspacesPage.test.js, ohara-manager/client/cypress/support/e2eCommands.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineEditPage/PipelineEditPage.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineToolbar/PipelineNewConnector.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineToolbar/PipelineToolbar.js, ohara-manager/client/src/components/pages/PipelinePage/PipelineToolbar/pipelineToolbarUtils.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Plugins/Plugins.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Plugins/usePlugin.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/StreamApp/StreamApp.js, ohara-manager/scripts/handleE2eServices.js
=> #2799 [Manager] Fix unstable E2E tests

docs/src/rest/rest-brokers.rst, docs/src/rest/rest-connectors.rst, ohara-agent/src/main/scala/com/island/ohara/agent/BrokerCollie.scala, ohara-agent/src/main/scala/com/island/ohara/agent/k8s/K8SBrokerCollieImpl.scala, ohara-agent/src/main/scala/com/island/ohara/agent/ssh/BrokerCollieImpl.scala, ohara-agent/src/test/scala/com/island/ohara/agent/FakeBrokerCollie.scala, ohara-agent/src/test/scala/com/island/ohara/agent/TestBrokerCreator.scala, ohara-client/src/main/scala/com/island/ohara/client/configurator/v0/BrokerApi.scala, ohara-client/src/test/scala/com/island/ohara/client/configurator/v0/TestBrokerApi.scala, ohara-configurator/src/main/scala/com/island/ohara/configurator/ConfiguratorBuilder.scala, ohara-configurator/src/main/scala/com/island/ohara/configurator/fake/FakeBrokerCollie.scala, ohara-configurator/src/main/scala/com/island/ohara/configurator/route/BrokerRoute.scala, ohara-configurator/src/main/scala/com/island/ohara/configurator/route/ZookeeperRoute.scala, ohara-configurator/src/test/scala/com/island/ohara/configurator/TestMixedFakeCollie.scala, ohara-configurator/src/test/scala/com/island/ohara/configurator/route/TestBrokerRoute.scala, ohara-configurator/src/test/scala/com/island/ohara/configurator/route/TestContainerRoute.scala, ohara-configurator/src/test/scala/com/island/ohara/configurator/route/TestStreamRoute.scala, ohara-configurator/src/test/scala/com/island/ohara/configurator/route/TestTopicRoute.scala, ohara-configurator/src/test/scala/com/island/ohara/configurator/route/TestWorkerRoute.scala, ohara-it/src/test/scala/com/island/ohara/it/agent/BasicTests4Collie.scala, ohara-it/src/test/scala/com/island/ohara/it/agent/BasicTests4StreamApp.scala, ohara-it/src/test/scala/com/island/ohara/it/agent/k8s/TestK8SSimpleCollie.scala, ohara-it/src/test/scala/com/island/ohara/it/agent/ssh/TestLoadCustomJarToWorkerCluster.scala, ohara-it/src/test/scala/com/island/ohara/it/connector/BasicTestConnectorCollie.scala, ohara-it/src/test/scala/com/island/ohara/it/connector/jio/BasicIntegrationTestsOfJsonIo.scala, ohara-it/src/test/scala/com/island/ohara/it/prometheus/TestPrometheus.scala
=> #2731 Broker APIs should honor cluster key

ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/TopicNewModal.js, ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesNewModal/WorkspacesNewModal.js, ohara-manager/client/src/utils/validate.js
=> #2894 [Manager] Don't start a topic if it's failed in the creation phase

docs/testcase/pipeline-jdbc-topic-ftp.md
edit and modify for 0.8.0 version test
=> #2882 Update UI test case 2 

ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/TopicNewModal.js, ohara-manager/client/src/utils/validate.js
=> #2942 [Manager] Should handle topic starting error

ohara-manager/client/src/components/pages/WorkspacesPage/WorkspacesDetailPage/Topics/TopicNewModal.js, ohara-manager/client/src/utils/validate.js
=> #2942 [Manager] Should handle topic starting error (backport to 0.8)

docs/src/user_guide.rst, kubernetes/distribute/k8s-pre-install.sh
=> #2926 Modify document to solve configurator permission issue and describe install K8S use the root permission

ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/source/JDBCSourceTask.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestJDBCSourceTaskRecovery.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestMultipleJDBCSourceConnector.scala
=> #2024 Test running multiple JDBC source connector to confirm data row count

ohara-agent/src/test/scala/com/island/ohara/agent/k8s/TestK8SClient.scala
=> #729 Added test code to test K8SClient configmap

docs/src/user_guide.rst
=> #3053 修改安裝 K8S 的文件

ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/datatype/CommonDataTypeConverter.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/datatype/DataTypeEnum.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/datatype/GenericDataTypeConverter.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/datatype/MySQLDataTypeConverter.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/datatype/OracleDataTypeConverter.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/datatype/PostgresqlDataTypeConverter.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/datatype/RDBDataTypeConverter.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/datatype/RDBDataTypeConverterFactory.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/source/DBTableDataProvider.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/source/JDBCSourceTask.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/source/QueryResultIterator.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/source/ResultSetDataConverter.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/source/package.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/datatype/TestMySQLDataTypeConverter.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/datatype/TestOracleDataTypeConverter.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/datatype/TestPostgresqlDataTypeConverter.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestJDBCSourceConnectorDataType.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestJDBCSourceTask.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestQueryResultIterator.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestResultSetDataConverter.scala, ohara-it/src/test/scala/com/island/ohara/it/connector/BasicTestConnectorCollie.scala, ohara-it/src/test/scala/com/island/ohara/it/connector/BasicTestOracleJDBCSourceConnector.scala, ohara-it/src/test/scala/com/island/ohara/it/connector/BasicTestPostgresqlJDBCSourceConnector.scala
這是一個草稿的 PR, 目前還有 Oracle DataType 的部份還沒實作完
=> #1733 Refactor DB datatype for JDBC Source Connector

docs/src/user_guide.rst, kubernetes/k8sproxyserver.service
=> #3084 Added autostart service for the Kubernetes API proxy server

ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestJDBCSourceConnector.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestJDBCSourceConnectorDataType.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestJDBCSourceConnectorRecovery.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestMultipleJDBCSourceConnector.scala
=> #3108 Delete the WorkerClient after JDBC source connector test complete

ohara-client/src/main/scala/com/island/ohara/client/configurator/v0/BrokerApi.scala, ohara-client/src/main/scala/com/island/ohara/client/configurator/v0/TopicApi.scala, ohara-client/src/main/scala/com/island/ohara/client/configurator/v0/WorkerApi.scala, ohara-client/src/main/scala/com/island/ohara/client/configurator/v0/ZookeeperApi.scala
=> #3152 Definitions have some wrong settings

ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/source/DBTableDataProvider.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/source/JDBCSourceConnector.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/source/JDBCSourceConnectorConfig.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/source/JDBCSourceTask.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/source/ResultSetDataConverter.scala, ohara-connector/src/main/scala/com/island/ohara/connector/jdbc/source/package.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestJDBCSourceConnectorConfig.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestJDBCSourceConnectorDefinition.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestJDBCSourceTask.scala, ohara-connector/src/test/scala/com/island/ohara/connector/jdbc/source/TestJDBCSourceTaskRecovery.scala
=> #3125 Added time frequence argument for JDBC source connector

ohara-manager/client/src/api/body/brokerBody.js, ohara-manager/client/src/api/body/connectorBody.js, ohara-manager/client/src/api/body/streamAppBody.js, ohara-manager/client/src/api/body/topicBody.js, ohara-manager/client/src/api/body/workerBody.js, ohara-manager/client/src/api/body/zookeeperBody.js, ohara-manager/client/src/api/brokerApi.js, ohara-manager/client/src/api/connectorApi.js, ohara-manager/client/src/api/infoApi.js, ohara-manager/client/src/api/streamAppApi.js, ohara-manager/client/src/api/topicApi.js, ohara-manager/client/src/api/utils/apiUtils.js, ohara-manager/client/src/api/utils/definitionsUtils.js, ohara-manager/client/src/api/utils/validation.js, ohara-manager/client/src/api/workerApi.js, ohara-manager/client/src/api/zookeeperApi.js
=> #3121 Manager API adds definition support

docs/src/user_guide.rst
=> #3189 Modify K8S install user guide document for Configurator request API format and URL location

ohara-agent/src/main/scala/com/island/ohara/agent/fake/FakeK8SClient.scala, ohara-agent/src/main/scala/com/island/ohara/agent/k8s/K8SClient.scala, ohara-agent/src/test/scala/com/island/ohara/agent/k8s/TestK8SClient.scala, ohara-configurator/src/main/scala/com/island/ohara/configurator/Configurator.scala, ohara-configurator/src/test/scala/com/island/ohara/configurator/TestConfigurator.scala, ohara-configurator/src/test/scala/com/island/ohara/configurator/TestConfiguratorMain.scala
=> #582 Added list all K8S nodes for configurator /v0/nodes API

docs/src/user_guide.rst, ohara-agent/src/main/scala/com/island/ohara/agent/fake/FakeK8SClient.scala, ohara-agent/src/main/scala/com/island/ohara/agent/k8s/K8SClient.scala, ohara-agent/src/main/scala/com/island/ohara/agent/k8s/K8SJson.scala, ohara-agent/src/main/scala/com/island/ohara/agent/k8s/K8SServiceCollieImpl.scala, ohara-agent/src/test/scala/com/island/ohara/agent/k8s/TestK8SClient.scala, ohara-agent/src/test/scala/com/island/ohara/agent/k8s/TestK8SServiceCollieImpl.scala, ohara-configurator/src/main/scala/com/island/ohara/configurator/Configurator.scala, ohara-configurator/src/main/scala/com/island/ohara/configurator/ConfiguratorBuilder.scala, ohara-it/build.gradle, ohara-it/src/test/scala/com/island/ohara/it/EnvTestingUtils.scala, ohara-it/src/test/scala/com/island/ohara/it/agent/BasicTests4Resources.scala, ohara-it/src/test/scala/com/island/ohara/it/agent/k8s/TestNodeResourcesOnK8S.scala
=> #3148 Enable k8s mode to offer resources to Node APIs

ohara-configurator/src/main/scala/com/island/ohara/configurator/Configurator.scala, ohara-configurator/src/main/scala/com/island/ohara/configurator/ConfiguratorBuilder.scala, ohara-configurator/src/test/scala/com/island/ohara/configurator/TestConfiguratorBuilder.scala
=> #3277 啟動 configurator 服務時 --k8s 參數沒有放在最後面會出錯誤

docs/src/user_guide.rst
=> #3276 Added install K8S metrics server document for user_guide.rst file

ohara-manager/client/cypress/configs/cypress.api.json, ohara-manager/client/package.json, ohara-manager/client/src/api/fileApi.js, ohara-manager/client/src/api/inspectApi.js, ohara-manager/client/src/api/utils/apiUtils.js, ohara-manager/client/src/api/utils/definitionsUtils.js, ohara-manager/client/src/components/Node/AddNodeDialog.js, ohara-manager/client/src/components/Node/NodeDialog.js, ohara-manager/client/src/components/Pipeline/IntroDialog.js, ohara-manager/client/src/components/Topic/AddTopicDialog.js, ohara-manager/client/src/components/Workspace/Card/FileCard.js, ohara-manager/client/src/components/Workspace/Card/SelectCard.js, ohara-manager/client/src/components/Workspace/Card/WorkspaceCard.js, ohara-manager/client/src/components/Workspace/WorkspaceQuick.js, ohara-manager/client/src/components/common/Dialog/FullScreenDialog.js, ohara-manager/client/src/components/common/Progress/Prcentage.js, ohara-manager/client/src/components/common/Table/SelectTable.js, ohara-manager/client/src/components/common/Table/index.js, ohara-manager/client/src/context/NodeDialogContext.js, ohara-manager/client/src/utils/__tests__/validate.test.js, ohara-manager/client/src/utils/validate.js, ohara-manager/client/yarn.lock
=>  #3157 New workspace quick mode

ohara-common/src/main/java/com/island/ohara/common/util/CommonUtils.java, ohara-configurator/src/main/scala/com/island/ohara/configurator/fake/FakeServiceCollie.scala
=> #3290 Added resource info to FakeServiceCollie implement

ohara-agent/src/main/scala/com/island/ohara/agent/k8s/K8SClient.scala, ohara-agent/src/test/scala/com/island/ohara/agent/k8s/TestK8SClient.scala
=> #3287 K8S Metrics Server API 的 resource usage 單位有可能變化

ohara-agent/src/main/scala/com/island/ohara/agent/BrokerCollie.scala, ohara-agent/src/main/scala/com/island/ohara/agent/StreamCollie.scala, ohara-agent/src/main/scala/com/island/ohara/agent/WorkerCollie.scala, ohara-agent/src/main/scala/com/island/ohara/agent/ZookeeperCollie.scala, ohara-agent/src/main/scala/com/island/ohara/agent/docker/ContainerState.scala
=> #3325 Added PENDING status to the toStatus function for ZookeeperCollie, BrokerCollie and WorkerCollie

ohara-agent/src/main/scala/com/island/ohara/agent/fake/FakeK8SClient.scala, ohara-agent/src/main/scala/com/island/ohara/agent/k8s/K8SClient.scala, ohara-agent/src/main/scala/com/island/ohara/agent/k8s/package.scala, ohara-agent/src/test/scala/com/island/ohara/agent/k8s/TestK8SClient.scala, ohara-configurator/src/main/scala/com/island/ohara/configurator/ConfiguratorBuilder.scala, ohara-configurator/src/test/scala/com/island/ohara/configurator/TestConfiguratorBuilder.scala, ohara-it/src/test/scala/com/island/ohara/it/EnvTestingUtils.scala
=> #3338 Modify build pattern for K8SClient create the object

ohara-manager/client/src/components/Pipeline/Graph/Connector/ConnectorGraph.js, ohara-manager/client/src/components/Pipeline/Graph/Connector/styles.js, ohara-manager/client/src/components/Pipeline/Graph/Graph.js, ohara-manager/client/src/components/Pipeline/Graph/GraphStyles.js, ohara-manager/client/src/components/Pipeline/Toolbox/Toolbox.js, ohara-manager/client/src/components/Pipeline/Toolbox/toolboxUtils.js
=>  #3292 Create pipeline graphs (connector,stream)

ohara-agent/src/main/scala/com/island/ohara/agent/k8s/K8SClient.scala, ohara-agent/src/test/scala/com/island/ohara/agent/k8s/TestK8SClient.scala
=> #3400 K8sClient.removePod does not wait the thread to complete

ohara-agent/src/main/scala/com/island/ohara/agent/docker/DockerClient.scala, ohara-it/src/test/scala/com/island/ohara/it/collie/BasicTests4Log.scala
=> #3424 Added --since argument for the DockerClient#log

ohara-configurator/src/main/scala/com/island/ohara/configurator/Configurator.scala
=> #3428 fix flaky TestConfigurator.testK8SNodes

ohara-it/docker/README.md, ohara-it/docker/core-site.sh, ohara-it/docker/datanode.dockerfile, ohara-it/docker/datanode.sh, ohara-it/docker/hdfs-container.sh, ohara-it/docker/hdfs-site.sh, ohara-it/docker/namenode.dockerfile, ohara-it/docker/namenode.sh
=> #3030 Write the script of building a min hdfs cluster

ohara-it/build.gradle, ohara-it/docker/core-site.sh, ohara-it/docker/hdfs-container.sh, ohara-it/docker/namenode.dockerfile, ohara-it/docker/namenode.sh, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4Hdfs.scala
=> #3030 Introduce performance test for HDFSSink

ohara-it/docker/README.md, ohara-it/docker/oracle-container.sh
=> #3030 Write the script of building a single oracle database

ohara-manager/client/src/api/connectorApi.js, ohara-manager/client/src/components/Pipeline/SettingDialog.js, ohara-manager/client/src/components/Pipeline/Toolbox/Toolbox.js, ohara-manager/client/src/components/Pipeline/Toolbox/ToolboxHooks.js, ohara-manager/client/src/components/Pipeline/Toolbox/toolboxUtils.js, ohara-manager/client/src/components/Workspace/WorkspaceQuick.js, ohara-manager/client/src/context/dialog/dialogReducer.js
=> #3516 Fix some bug in create workspace

ohara-manager/client/src/api/utils/definitionsUtils.js, ohara-manager/client/src/components/Pipeline/SettingDefinitions.js, ohara-manager/client/src/components/common/Definitions/ArrayDef.js, ohara-manager/client/src/components/common/Definitions/BindingPort.js, ohara-manager/client/src/components/common/Definitions/BooleanDef.js, ohara-manager/client/src/components/common/Definitions/ClassDef.js, ohara-manager/client/src/components/common/Definitions/Double.js, ohara-manager/client/src/components/common/Definitions/Duration.js, ohara-manager/client/src/components/common/Definitions/IntDef.js, ohara-manager/client/src/components/common/Definitions/JdbcTable.js, ohara-manager/client/src/components/common/Definitions/Long.js, ohara-manager/client/src/components/common/Definitions/Password.js, ohara-manager/client/src/components/common/Definitions/Permission.js, ohara-manager/client/src/components/common/Definitions/Port.js, ohara-manager/client/src/components/common/Definitions/PositiveDouble.js, ohara-manager/client/src/components/common/Definitions/PositiveInt.js, ohara-manager/client/src/components/common/Definitions/PositiveLong.js, ohara-manager/client/src/components/common/Definitions/PositiveShort.js, ohara-manager/client/src/components/common/Definitions/RenderDefinition.js, ohara-manager/client/src/components/common/Definitions/RenderDefinitions.js, ohara-manager/client/src/components/common/Definitions/Short.js, ohara-manager/client/src/components/common/Definitions/StringDef.js, ohara-manager/client/src/components/common/Definitions/Tags.js, ohara-manager/client/src/utils/validate.js
=> #3466 Add new flag "updatable" and regular to manager

ohara-it/docker/README.md, ohara-it/docker/samba-container.sh, ohara-it/docker/samba.dockerfile, ohara-it/docker/samba.sh
=> #3030 Write the script of building a single smb server

ohara-manager/client/cypress/api/pipelineApi.test.js, ohara-manager/client/src/AppProviders.js, ohara-manager/client/src/api/body/pipelineBody.js, ohara-manager/client/src/components/Pipeline/Graph/Topic/TopicGraph.js, ohara-manager/client/src/components/Pipeline/Navigator/Navigator.js, ohara-manager/client/src/components/Pipeline/Toolbox/Toolbox.js, ohara-manager/client/src/components/Pipeline/Toolbox/toolboxUtils.js, ohara-manager/client/src/components/Topic/AddTopicDialog.js, ohara-manager/client/src/context/index.js, ohara-manager/client/src/context/pipeline/PipelineContext.js, ohara-manager/client/src/context/pipeline/pipelineActions.js, ohara-manager/client/src/context/pipeline/pipelineReducer.js, ohara-manager/client/src/context/stream/StreamContext.js, ohara-manager/client/src/context/stream/streamActions.js, ohara-manager/client/src/context/stream/streamReducer.js, ohara-manager/client/src/context/stream/streamRoutines.js
=> #3572 Saving graph in manager pipeline

ohara-client/src/main/scala/com/island/ohara/client/filesystem/ftp/FtpClient.scala, ohara-client/src/main/scala/com/island/ohara/client/filesystem/smb/SmbFileSystem.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Ftp.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4FtpSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4HdfsSink.scala
=> #3030 Introduce performance test for FtpSink

ohara-manager/client/src/components/Pipeline/Graph/Connector/ConnectorGraph.js, ohara-manager/client/src/components/Pipeline/Graph/Graph.js, ohara-manager/client/src/components/Pipeline/Graph/Topic/TopicGraph.js, ohara-manager/client/src/components/Pipeline/SettingDefinitions.js, ohara-manager/client/src/components/Pipeline/Toolbox/Toolbox.js, ohara-manager/start.js
=> #3572 Save graph in pipeline

ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Jdbc.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Samba.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4FtpSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4FtpSource.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4HdfsSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4JsonOut.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4PerfSource.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4SambaSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4SambaSource.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4Topic.scala
=> #3030  Introduce performance test for Samba

ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4FtpSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4HdfsSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4SambaSink.scala
=> #3674 performance 測試程式的 afterStoppingConnector 方法忘了加上 protected

ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Ftp.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Samba.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4FtpSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4FtpSource.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4HdfsSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4SambaSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4SambaSource.scala
=> #3688 Refactor the afterStoppingConnectors function for TestPerformance4FtpSink, TestPerformance4HdfsSink and TestPerformance4SambaSink

ohara-manager/client/package.json, ohara-manager/client/src/api/inspectApi.js, ohara-manager/client/src/api/utils/apiUtils.js, ohara-manager/client/src/components/Pipeline/Graph/Connector/ConnectorGraph.js, ohara-manager/client/src/components/Pipeline/Graph/Graph.js, ohara-manager/client/src/components/Pipeline/Graph/Topic/TopicGraph.js, ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/components/Pipeline/SettingDefinitions.js, ohara-manager/client/src/components/Pipeline/SettingDialog.js, ohara-manager/client/src/components/Pipeline/Toolbox/Toolbox.js, ohara-manager/client/src/components/Pipeline/Toolbox/toolboxUtils.js, ohara-manager/client/src/components/common/Definitions/Reference.js, ohara-manager/client/src/components/common/Definitions/RenderDefinition.js, ohara-manager/client/src/components/common/Definitions/RenderDefinitions.js, ohara-manager/client/src/context/connector/connectorActions.js, ohara-manager/client/yarn.lock
=> #3649 Connector actions (start, stop, delete, configure)

ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance.scala
=> #3679 Increase size of input data for performance test

ohara-manager/client/src/api/inspectApi.js, ohara-manager/client/src/components/Pipeline/Graph/Connector/ConnectorGraph.js, ohara-manager/client/src/components/Pipeline/Graph/Graph.js, ohara-manager/client/src/components/Pipeline/Graph/Topic/TopicGraph.js, ohara-manager/client/src/components/Pipeline/Toolbox/Toolbox.js, ohara-manager/client/src/components/Pipeline/Toolbox/toolboxUtils.js, ohara-manager/client/src/components/common/Definitions/Reference.js, ohara-manager/client/src/components/common/Definitions/RenderDefinition.js, ohara-manager/client/src/components/common/Definitions/Tags.js, ohara-manager/client/src/context/pipeline/pipelineActions.js
=> #3701 fix some pipeline settingDialog defined bugs

ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Ftp.scala
=> #3707 BasicTestPerformance4Ftp#removeFtpFolder 不能移除空資料夾

ohara-it/src/test/scala/com/island/ohara/it/WithRemoteWorkers.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance.scala
=> #3665 Before start the connector, await worker http server completed for performance test

docs/src/rest/rest-topics.rst
=> #3744 Modify topic api for the docs

ohara-manager/client/src/components/Pipeline/Graph/Connector/ConnectorGraph.js, ohara-manager/client/src/components/Pipeline/Graph/Graph.js, ohara-manager/client/src/components/Pipeline/Graph/Topic/TopicGraph.js, ohara-manager/client/src/components/Pipeline/Graph/graphUtils.js, ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/components/Pipeline/SettingDialog.js, ohara-manager/client/src/context/connector/ConnectorContext.js, ohara-manager/client/src/context/connector/connectorActions.js, ohara-manager/client/src/context/topic/TopicContext.js, ohara-manager/client/src/context/topic/topicActions.js
=> #3693 Graph updates automatically when connector updates

docs/src/rest/rest-validation.rst
=> #3744 Revise Validation APIs document

docs/src/rest/rest-nodes.rst
=> #3744 Apply version variable to rest-nodes.rst file

docs/src/rest/rest-containers.rst
=> #3744  Revise Container APIs document

docs/src/rest/rest-pipelines.rst
=> #3744 Revise Pipeline APIs document

docs/src/rest/rest-logs.rst
=> #3744 Revise Logs APIs document

docs/src/rest/rest-objects.rst
=> #3744 Revise Object APIs document

docs/src/rest/rest-inspect.rst
=> #3744 Revise Inspect APIs document

docs/src/rest/rest-files.rst, docs/src/rest/rest-streams.rst, docs/src/rest/rest-workers.rst
=> #3744  Revise Files APIs document 

docs/src/rest/rest-inspect.rst, docs/src/rest/rest-streams.rst
=> #3744 Revise Stream APIs document

docs/src/rest/rest-logs.rst, docs/src/rest/rest-pipelines.rst, docs/src/rest/rest-streams.rst
=> #3744 Fix document write error for the rest api

docs/src/rest/rest-brokers.rst, docs/src/rest/rest-connectors.rst, docs/src/rest/rest-inspect.rst, docs/src/rest/rest-streams.rst, docs/src/rest/rest-topics.rst, docs/src/rest/rest-workers.rst
=> #3744 修改 rest api 文件項目數字排版

ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Jdbc.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4FtpSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4FtpSource.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4HdfsSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4JDBCSourceToHDFSSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4JsonOut.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4Oracle.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4SambaSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4SambaSource.scala
=> #3881 Add performance case of transferring data from database to hdfs

ohara-it/src/test/scala/com/island/ohara/it/performance/HDFSPerformanceTestingUtils.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/PerformanceTestingUtils.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4FtpSourceToHDFSSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4HdfsSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4JDBCSourceToHDFSSink.scala
=> #3881 Add performance case of transferring data from ftp to hdfs

ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/apiHelperUtils.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/connector.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/index.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/stream.js, ohara-manager/client/src/const.js
=> #3812 Paper disconnect action

ohara-manager/client/src/components/Pipeline/Paper/Paper.js, ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/connector.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/stream.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyDialog/PipelinePropetyDialog.js, ohara-manager/client/src/components/common/Definitions/ArrayDef.js, ohara-manager/client/src/components/common/Definitions/Reference.js, ohara-manager/client/src/context/connector/connectorActions.js
=> #3812 Paper config action with Connector and Stream api

ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/connector.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/index.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/pipeline.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/stream.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/topic.js
=> #3812 Paper onChange action with Pipeline API

ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Ftp.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Jdbc.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Samba.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/PerformanceTestingUtils.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4HdfsSink.scala
=> #3909 Performance test code key move to PerformanceTestingUtils object

ohara-it/docker/datanode.dockerfile, ohara-it/docker/datanode.sh, ohara-it/docker/ftp-container.sh, ohara-it/docker/ftp.sh, ohara-it/docker/hdfs-container.sh, ohara-it/docker/namenode.dockerfile, ohara-it/docker/namenode.sh, ohara-it/docker/oracle-container.sh, ohara-it/docker/samba-container.sh, ohara-it/docker/samba.sh, ohara-it/docker/start-service.sh, ohara-it/docker/stop-service.sh
=> #3913 Added volume argument to running docker container for expose host path

ohara-manager/client/src/components/Pipeline/Paper/Paper.js, ohara-manager/client/src/components/Pipeline/Paper/cell/createConnectorCell.js, ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/components/Pipeline/PipelineHooks.js, ohara-manager/client/src/context/pipeline/pipelineActions.js, ohara-manager/client/src/context/pipeline/pipelineReducer.js, ohara-manager/client/src/context/pipeline/pipelineRoutines.js
=> #3812 Paper Metrics update with pipeline API

ohara-it/docker/oracle-container.sh
=> #3966 fix flaky oracle-container.sh

ohara-manager/client/src/components/Pipeline/Paper/Paper.js, ohara-manager/client/src/components/Pipeline/Paper/cell/createTopicCell.js, ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/pipeline.js, ohara-manager/client/src/context/connector/ConnectorContext.js
=> #3975 [Manager] Update paper cells property with onInit event

ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Ftp.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Jdbc.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Samba.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/PerformanceTestingUtils.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4FtpSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4FtpSource.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4FtpSourceToHDFSSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4HdfsSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4JDBCSourceToHDFSSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4JsonOut.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4Oracle.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4SambaSink.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/TestPerformance4SambaSource.scala
=> #3881 Add generator data function to sleepUntilEnd function for performance test

ohara-manager/client/src/context/worker/workerActions.js
=> #3987 [Manager] Cannot get the connector list on initial page load

ohara-manager/client/src/components/Pipeline/PipelineApiHelper/pipeline.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyDialog/PipelinePropetyDialog.js, ohara-manager/client/src/components/Workspace/Edit/EditWorkspace.js, ohara-manager/client/src/components/Workspace/Edit/MoreActions.js, ohara-manager/client/src/components/common/Definitions/Reference.js
=> #3983 [Manager] Reset Workspace

ohara-manager/client/src/components/Pipeline/Pipeline.js
=> #3994 [Manager] Topic element force delete

ohara-manager/client/src/components/Pipeline/PipelinePropertyDialog/PipelinePropetyDialog.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyDialog/SettingDefinitions.js, ohara-manager/client/src/components/Workspace/Create/WorkspaceQuick.js, ohara-manager/client/src/components/common/Definitions/BindingPort.js, ohara-manager/client/src/components/common/Definitions/RenderDefinition.js, ohara-manager/client/src/components/common/Definitions/RenderDefinitions.js
=> #4001 In the workspace quick create should be random freePort

ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/apiHelperUtils.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/stream.js
=> #4000 Paper should be stream to stream auto create

ohara-manager/client/src/components/Pipeline/Toolbox/ToolboxHooks.js, ohara-manager/client/src/components/common/Definitions/ArrayDef.js
=> #4011 [Manager] Toolbox upload multiple stream some time are failed

ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/BasicTestPerformance4Jdbc.scala, ohara-it/src/test/scala/com/island/ohara/it/performance/PerformanceTestingUtils.scala
=> #3991 Performance 測試程式 wholeTimeout 需要用 duration time 設定

ohara-manager/client/src/components/Pipeline/PipelineApiHelper/pipeline.js
=> #4027 [Manager] Shared topic is not saved in the backend

ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance4Ftp.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance4Jdbc.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance4Samba.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/PerformanceTestingUtils.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4FtpSink.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4FtpSource.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4FtpSourceToHDFSSink.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4HdfsSink.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4JDBCSourceToHDFSSink.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4JsonOut.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4Oracle.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4SambaSink.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4SambaSource.scala
=> #4016 Added setup data time limit and input data thread for the Performance test

ohara-manager/client/src/components/Pipeline/Paper/Paper.js, ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/pipeline.js, ohara-manager/client/src/components/Pipeline/PipelineHooks.js, ohara-manager/client/src/context/connector/ConnectorContext.js, ohara-manager/client/src/context/connector/connectorReducer.js, ohara-manager/client/src/context/connector/connectorRoutines.js, ohara-manager/client/src/context/pipeline/PipelineContext.js, ohara-manager/client/src/context/stream/StreamContext.js, ohara-manager/client/src/context/stream/streamReducer.js, ohara-manager/client/src/context/stream/streamRoutines.js
=> #3813 Reset pipeline state when switching between different pipelines

ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance4Ftp.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance4Jdbc.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance4Samba.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/PerformanceDataMetricsFile.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/PerformanceTestingUtils.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4FtpSink.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4FtpSource.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4FtpSourceToHDFSSink.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4HdfsSink.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4JDBCSourceToHDFSSink.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4JsonOut.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4Oracle.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4SambaSink.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4SambaSource.scala
=> #4015 Added input data number and size for the performance test

ohara-manager/client/cypress/configs/cypress.e2e.json, ohara-manager/client/src/api/utils/definitionsUtils.js, ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyView/PipelinePropertyView.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyView/PipelinePropertyViewField.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyView/PipelinePropertyViewFieldStyles.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyView/PipelinePropertyViewStyles.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyView/PipelinePropertyViewUtils.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyView/index.js, ohara-manager/client/src/components/common/Dialog/Dialog.js, ohara-manager/client/src/theme/muiTheme.js
=> #3949 Pipeline page element property view (render with settings)

ohara-manager/client/src/components/Pipeline/Paper/Paper.js, ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/connector.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/stream.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyDialog/PipelinePropertyDialog.js, ohara-manager/client/src/components/common/Definitions/Table.js
=> #4105 OBJECT_KEYS and TABLE save has some strange behavior

ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/context/connector/ConnectorContext.js, ohara-manager/client/src/context/stream/StreamContext.js
=> #4107 Reset pipeline state when switching between different pipelines

ohara-manager/client/src/components/Pipeline/PipelineApiHelper/pipeline.js
=> #4087 [Manager] Un-added shared topic will be removed after reload page

ohara-manager/client/src/components/Pipeline/Toolbox/Toolbox.js
=> #4122 [Manager] Metrics data update resets Toolbox's scroll position

ohara-manager/client/src/components/Pipeline/PipelineApiHelper/pipeline.js, ohara-manager/client/src/components/Pipeline/PipelineApiHelper/topic.js, ohara-manager/client/src/context/pipeline/pipelineReducer.js
=> #4148 [Manager] Multiple pipeline running problem

ohara-it/src/test/scala/oharastream/ohara/it/ServiceKeyHolder.scala
=> #4191 Added sinceSeconds setting to get docker container log for the test

ohara-it/src/test/scala/oharastream/ohara/it/ServiceKeyHolder.scala
=> #4192 Added sinceSeconds setting to get docker container log for the test 

ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/PerformanceReport.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformanceReport.scala
=> #4125 Performance test 在 connector 設定多個 tasks，metrics data 會被覆寫

ohara-manager/client/src/api/utils/definitionsUtils.js, ohara-manager/client/src/components/Pipeline/Pipeline.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyView/PipelinePropertyView.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyView/PipelinePropertyViewField.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyView/PipelinePropertyViewUtils.js
=> #4190 [Manager] Hide the group info from Property view

ohara-connector/src/main/scala/oharastream/ohara/connector/ftp/package.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/ftp/TestFtpSourceConnector.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/ftp/TestFtpSourceTask.scala, ohara-kafka/src/main/java/oharastream/ohara/kafka/connector/csv/CsvConnectorDefinitions.java, ohara-kafka/src/main/java/oharastream/ohara/kafka/connector/csv/CsvSourceConnector.java, ohara-kafka/src/main/java/oharastream/ohara/kafka/connector/csv/CsvSourceTask.java, ohara-kafka/src/main/java/oharastream/ohara/kafka/connector/csv/source/CsvSourceConfig.java, ohara-kafka/src/test/java/oharastream/ohara/kafka/connector/csv/TestCsvSourceTask.java
=> #4219 Cache the file paths to reduce the count of expensive LIST operations

ohara-manager/client/src/components/Node/NodeDialog.js, ohara-manager/client/src/components/common/Progress/Percentage.js
=> #4263 Node list columns display incorrect when node is dead

ohara-manager/client/cypress/e2e/nodeDialog.test.js, ohara-manager/client/src/components/Node/NodeDialog.js, ohara-manager/client/src/components/common/Table/SelectTable.js
=> #4251 [Manager] Nodes page need display node state

ohara-manager/client/src/components/Pipeline/PipelineApiHelper/topic.js
=> #4274 [Manager] Create two topics at the same time in Paper will break the UI

ohara-client/src/main/scala/oharastream/ohara/client/filesystem/hdfs/HdfsFileSystem.scala, ohara-connector/src/main/scala/oharastream/ohara/connector/hdfs/sink/HDFSSink.scala, ohara-connector/src/main/scala/oharastream/ohara/connector/hdfs/sink/HDFSSinkProps.scala, ohara-connector/src/main/scala/oharastream/ohara/connector/hdfs/sink/HDFSSinkTask.scala, ohara-connector/src/main/scala/oharastream/ohara/connector/hdfs/sink/package.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/hdfs/sink/TestHDFSSinkConfig.scala
=> #4261 HDFS Sink Connector 需要設定副本的參數

ohara-manager/client/src/components/Pipeline/PipelinePropertyView/PipelinePropertyView.js
=> #4332 [Manager]Incorrect node items

ohara-it/src/test/scala/oharastream/ohara/it/performance/BasicTestPerformance.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/PerformanceTestingUtils.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4FtpSource.scala, ohara-it/src/test/scala/oharastream/ohara/it/performance/TestPerformance4SambaSource.scala
=> #4406 Added fileNameCacheSize parameter for the performance test

ohara-manager/client/src/components/Node/AddNodeDialog.js, ohara-manager/client/src/components/Node/EditNodeDialog.js, ohara-manager/client/src/components/Node/NodeDialog.js, ohara-manager/client/src/components/Node/ViewNodeDialog.js, ohara-manager/client/src/components/Pipeline/PipelinePropertyView/PipelinePropertyView.js, ohara-manager/client/src/components/Workspace/Edit/Settings/Nodes/Nodes.js, ohara-manager/client/src/hooks/nodeHooks.js, ohara-manager/client/src/store/actions/index.js, ohara-manager/client/src/store/actions/nodeActions.js, ohara-manager/client/src/store/epics/index.js, ohara-manager/client/src/store/epics/nodeEpics.js, ohara-manager/client/src/store/reducers/entities/index.js, ohara-manager/client/src/store/reducers/entities/nodes.js, ohara-manager/client/src/store/reducers/ui/index.js, ohara-manager/client/src/store/reducers/ui/node.js, ohara-manager/client/src/store/schema/index.js, ohara-manager/client/src/store/selectors/index.js, ohara-manager/client/src/store/selectors/nodeSelector.js
=> #4322 [Manager] Refactor nodes API with Redux

ohara-it/src/test/scala/oharastream/ohara/it/ContainerPlatform.scala
=> #4534 Modify typo for the ContainerPlatform object

ohara-manager/client/cypress/e2e/nodeDialog.test.ts, ohara-manager/client/cypress/e2e/pipeline.test.ts, ohara-manager/client/cypress/e2e/topicDialog.test.ts, ohara-manager/client/cypress/support/defaultCommands.ts, ohara-manager/client/src/components/Node/SelectNodeDialog.js, ohara-manager/client/src/components/common/Table/MuiTable.js, ohara-manager/client/src/components/common/Table/index.js, ohara-manager/client/src/utils/generate.ts
=> #4470 [Manager] Create workspace node list card table icon is broken

docs/src/how_to_build.rst, docs/testcase/ohara-installation.md, kubernetes/distribute/k8s-master-install.sh, kubernetes/distribute/k8s-pre-install.sh, kubernetes/distribute/k8s-worker-install.sh
=> #4530 Upgrade kubernetes version to 1.18.1 for the ohara shell script

docs/src/user_guide.rst, docs/testcase/ohara-installation.md
=> #4546 Modify path for the install k8s metrics-server document

ohara-agent/src/main/scala/oharastream/ohara/agent/k8s/K8SClient.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/k8s/K8SJson.scala, ohara-it/src/test/scala/oharastream/ohara/it/collie/TestContainerClient.scala
=> #4460 Add volume support to K8sClient

ohara-manager/client/src/hooks/connectorHooks.js, ohara-manager/client/src/hooks/topicHooks.js, ohara-manager/client/src/store/epics/connector/fetchConnectorsEpic.js, ohara-manager/client/src/store/reducers/entities/connectors.js, ohara-manager/client/src/store/schema/index.js, ohara-manager/client/src/store/selectors/connectorSelector.js, ohara-manager/client/src/store/selectors/topicSelector.js
=> #4456 [Manager] Make sure the pipeline all function is normal

ohara-it/src/test/scala/oharastream/ohara/it/collie/TestContainerClient.scala
=> #4574 Modify TestContainerClient#testVolume test code

ohara-manager/client/src/components/Workspace/Settings/DangerZone/RestartWorkspace.js, ohara-manager/client/src/components/Workspace/Settings/DangerZone/index.js, ohara-manager/client/src/components/Workspace/Settings/Settings.js, ohara-manager/client/src/components/Workspace/Settings/SettingsHooks.js, ohara-manager/client/src/components/common/Progress/LogProgress.js, ohara-manager/client/src/hooks/index.js, ohara-manager/client/src/hooks/restartWorkspaceHooks.js, ohara-manager/client/src/store/actions/deleteWorkspaceActions.js, ohara-manager/client/src/store/actions/index.js, ohara-manager/client/src/store/actions/restartWorkspaceActions.js, ohara-manager/client/src/store/epics/workspace/index.js, ohara-manager/client/src/store/epics/workspace/restartWorkspaceEpic.js, ohara-manager/client/src/store/reducers/ui/index.js, ohara-manager/client/src/store/reducers/ui/restartWorkspace.js, ohara-manager/client/src/utils/object.js
=> #4521 [Manager]Restart Progress Dialog

ohara-manager/client/src/api/__mocks__/logApi.ts, ohara-manager/client/src/api/apiInterface/logInterface.ts, ohara-manager/client/src/api/logApi.ts, ohara-manager/client/src/components/DevTool/Header/Controller/ControllerLog.js, ohara-manager/client/src/components/DevTool/Header/Header.js, ohara-manager/client/src/hooks/devToolHooks.js, ohara-manager/client/src/store/epics/__tests__/devTool/fetchLogEpic.test.js, ohara-manager/client/src/store/epics/__tests__/devTool/fetchTopicDataEpic.test.js, ohara-manager/client/src/store/epics/__tests__/devTool/setDevToolLogQueryParamsEpic.test.js, ohara-manager/client/src/store/epics/devTool/fetchLogEpic.js, ohara-manager/client/src/store/epics/devTool/setDevToolLogQueryParamsEpic.js, ohara-manager/client/src/store/reducers/entities/index.js, ohara-manager/client/src/store/reducers/ui/devTool.js, ohara-manager/client/src/store/reducers/ui/index.js, ohara-manager/client/src/store/selectors/devToolSelector.js
=> #4735 [Manager] Support querying Shabondi logs

ohara-manager/client/src/components/Workspace/Settings/DangerZone/DeleteWorkspace.js, ohara-manager/client/src/components/Workspace/Settings/DangerZone/RestartWorkspace.js, ohara-manager/client/src/components/common/Progress/LogProgress.js, ohara-manager/client/src/hooks/restartWorkspaceHooks.js, ohara-manager/client/src/store/epics/workspace/restartWorkspaceEpic.js, ohara-manager/client/src/store/reducers/ui/deleteWorkspace.js, ohara-manager/client/src/store/reducers/ui/restartWorkspace.js
=> #4741 [Manager] Fix related bugs in restart and delete dialogs

ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/JDBCSourceTask.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTaskOffset.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTaskRecovery.scala
=> #4813 Update memory offset to recovery for the JDBC source connector

ohara-manager/client/src/store/reducers/ui/deleteWorkspace.js, ohara-manager/client/src/store/reducers/ui/restartWorkspace.js
=>  #4838 [Manager]The close button is sometimes not disabled when restarting and deleting

ohara-manager/client/src/api/apiInterface/definitionInterface.ts, ohara-manager/client/src/components/Pipeline/PipelinePropertyDialog/PipelinePropertyForm.js, ohara-manager/client/src/components/common/Definitions/Chooser.js, ohara-manager/client/src/components/common/Definitions/RenderDefinition.js, ohara-manager/client/src/store/reducers/entities/shabondis.js
=> #4736 [Manager] Shabondi nodeNames definition use reference setting

docs/src/user_guide.rst
=> #4855 Modify document for the install K8S metrics service

ohara-manager/client/src/components/Layout/NodeListDialog.js, ohara-manager/client/src/components/Node/NodeTable.js, ohara-manager/client/src/components/Workspace/CreateWorkspace/NodesField.js, ohara-manager/client/src/components/Workspace/Settings/pages/WorkspaceNodesPage.js, ohara-manager/client/src/hooks/workspaceHooks.js
=> #4812 [Manager] Manually fetch the node list

ohara-manager/client/src/components/File/FileSelectorDialog.js, ohara-manager/client/src/components/File/FileTable.js, ohara-manager/client/src/components/Node/NodeSelectorDialog.js, ohara-manager/client/src/components/Node/NodeTable.js, ohara-manager/client/src/components/Topic/TopicTable.js, ohara-manager/client/src/components/Workspace/Settings/pages/BrokerNodesPage.js, ohara-manager/client/src/components/Workspace/Settings/pages/StreamJarsPage.js, ohara-manager/client/src/components/Workspace/Settings/pages/WorkerNodesPage.js, ohara-manager/client/src/components/Workspace/Settings/pages/WorkerPluginsPage/PluginTable.js, ohara-manager/client/src/components/Workspace/Settings/pages/WorkerPluginsPage/SharedJarTable.js, ohara-manager/client/src/components/Workspace/Settings/pages/ZookeeperNodesPage.js, ohara-manager/client/src/components/common/Table/MuiTable.js
=> #4870 [Manager] The documention of definition should be shown

ohara-manager/client/src/components/File/Action.js, ohara-manager/client/src/components/File/Actions.js, ohara-manager/client/src/components/File/FileTable.js, ohara-manager/client/src/components/Workspace/Settings/pages/WorkspaceFilesPage.js
=> #4872 [Manager] Show reasons why files connot be deleted

ohara-manager/client/src/components/Workspace/Settings/Settings.js, ohara-manager/client/src/components/Workspace/Settings/SettingsHooks.js, ohara-manager/client/src/store/epics/workspace/restartWorkspaceEpic.js
=> #4790 [Bug] When the topic is running, the workspace restart will fail

ohara-manager/client/src/components/File/FileClassInfoDialog.js, ohara-manager/client/src/components/File/FileTable.js
=> #4873 [Manager] Preview the contents of the file

ohara-manager/client/src/components/File/FileTable.js, ohara-manager/client/src/components/File/index.js, ohara-manager/client/src/components/Workspace/Settings/SettingsMainStyles.js, ohara-manager/client/src/components/Workspace/Settings/SettingsStyles.js, ohara-manager/client/src/components/Workspace/Settings/common/WorkspaceFileSelectorDialog.js, ohara-manager/client/src/components/Workspace/Settings/common/WorkspaceFileTable.js, ohara-manager/client/src/components/Workspace/Settings/pages/StreamJarsPage.js, ohara-manager/client/src/components/Workspace/Settings/pages/WorkerPluginsPage/PluginTable.js, ohara-manager/client/src/components/Workspace/Settings/pages/WorkerPluginsPage/SharedJarTable.js, ohara-manager/client/src/components/Workspace/Settings/pages/WorkspaceFilesPage.js
=> #4905 [Manager] File selector should support deletion

ohara-manager/client/src/components/Node/NodeServiceTable.js
=> #4997 [Manager] Services table should not appear selection

ohara-common/src/test/java/oharastream/ohara/common/cache/TestCache.java, ohara-common/src/test/java/oharastream/ohara/common/rule/OharaTest.java, ohara-common/src/test/java/oharastream/ohara/common/rule/TestOharaTest.java, ohara-common/src/test/java/oharastream/ohara/common/setting/TestSettingDef.java, ohara-common/src/test/java/oharastream/ohara/common/util/TestCommonUtils.java, ohara-kafka/src/test/java/oharastream/ohara/kafka/TestTopicAdmin.java, ohara-kafka/src/test/java/oharastream/ohara/kafka/connector/TestConnectorProps.java, ohara-kafka/src/test/java/oharastream/ohara/kafka/connector/TestConnectorUtils.java, ohara-kafka/src/test/java/oharastream/ohara/kafka/connector/TestTaskSetting.java, ohara-kafka/src/test/java/oharastream/ohara/kafka/connector/json/TestConnectorDefUtils.java
=> #5001 Replace assertException by Assert.assertThrows

ohara-manager/client/src/hooks/deleteWorkspaceHooks.js, ohara-manager/client/src/store/epics/file/deleteFileEpic.js, ohara-manager/client/src/store/epics/workspace/deleteWorkspaceEpic.js
=> #4796 [Bug] Should delete related files when delete workspace

ohara-manager/client/src/components/Topic/TopicTable.js
=> #5068 [Manager] Prevent to show selection in the topic table

ohara-manager/client/src/components/Node/NodeTable.js
=> #5072 [Manager] Support more complete filters in node table

ohara-manager/client/src/components/common/Progress/LogProgress.js, ohara-manager/client/src/components/common/Progress/Progress.js
=>  #5052 [Manager]Progress bar sometimes appears abnormally

ohara-manager/client/src/hooks/restartWorkspaceHooks.js, ohara-manager/client/src/store/epics/broker/updateBrokerEpic.js, ohara-manager/client/src/store/epics/worker/updateWorkerEpic.js, ohara-manager/client/src/store/epics/workspace/restartWorkspaceEpic.js, ohara-manager/client/src/store/epics/zookeeper/updateZookeeperEpic.js, ohara-manager/client/src/store/reducers/ui/restartWorkspace.js
=> #4765 [Manager]RestartWorkspace errors will not be handled

ohara-manager/client/cypress/e2e/nodeDialog.test.ts, ohara-manager/client/src/components/Node/ClusterStateChip.js, ohara-manager/client/src/components/Node/NodeInfoTable.js, ohara-manager/client/src/components/Node/NodeServiceTable.js, ohara-manager/client/src/components/Node/NodeStateChip.js, ohara-manager/client/src/components/Node/NodeTable.js
=> #5085 [Manager] Highlight information about unavailable nodes

gradle.properties
=> #4706 Change branch versions from master to 0.10.x

ohara-agent/src/main/scala/oharastream/ohara/agent/docker/ServiceCollieImpl.scala
=> #5090 Service cache does not update the shabondi (#5094)

ohara-manager/client/src/store/reducers/ui/restartWorkspace.js
=> #5102 [Manager]Progress bar sometimes will be affected by other actions

ohara-manager/client/src/components/common/RenderCount.js
=> #5140 [Manager] Creates a component to appear count of re-render

ohara-manager/client/src/components/Workspace/Settings/DangerZone/RestartWorkspace.js, ohara-manager/client/src/components/common/Progress/LogProgress.js, ohara-manager/client/src/store/epics/workspace/restartWorkspaceEpic.js
=> #5139 Restart workspace should refer to the backend data at each step

ohara-manager/client/src/components/Workspace/Settings/Settings.js, ohara-manager/client/src/components/Workspace/Settings/SettingsHooks.js, ohara-manager/client/src/const.ts, ohara-manager/client/src/hooks/restartWorkspaceHooks.js, ohara-manager/client/src/store/epics/workspace/restartWorkspaceEpic.js, ohara-manager/client/src/store/reducers/ui/restartWorkspace.js
=> #5139 Support small scale restart workspace

ohara-manager/client/src/components/common/Progress/LogProgress.js, ohara-manager/client/src/components/common/Progress/LogRow.js, ohara-manager/client/src/components/common/Progress/LogRowStyles.js, ohara-manager/client/src/hooks/index.js, ohara-manager/client/src/hooks/logProgressHooks.js, ohara-manager/client/src/hooks/restartWorkspaceHooks.js, ohara-manager/client/src/store/actions/index.js, ohara-manager/client/src/store/actions/logProgressAction.js, ohara-manager/client/src/store/epics/index.js, ohara-manager/client/src/store/epics/logProgress/clearLogProgressEpic.js, ohara-manager/client/src/store/epics/logProgress/createLogProgressEpic.js, ohara-manager/client/src/store/epics/logProgress/index.js, ohara-manager/client/src/store/epics/workspace/restartWorkspaceEpic.js, ohara-manager/client/src/store/reducers/ui/index.js, ohara-manager/client/src/store/reducers/ui/logProgress.js, ohara-manager/client/src/store/selectors/logProgressSelector.js
=> #5139 Restart workspace display failed log

ohara-agent/src/main/scala/oharastream/ohara/agent/k8s/K8SClient.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/k8s/K8SJson.scala
=> #5234 Fix flaky TestContainerClient.testVolume (k8s mode)

ohara-manager/client/src/observables/__tests__/workers.test.js, ohara-manager/client/src/observables/index.js, ohara-manager/client/src/observables/internal/__tests__/retry.test.js, ohara-manager/client/src/observables/internal/deferApi.ts, ohara-manager/client/src/observables/internal/retry.ts, ohara-manager/client/src/observables/internal/strategies.ts, ohara-manager/client/src/observables/internal/utils.ts, ohara-manager/client/src/observables/utils.ts, ohara-manager/client/src/observables/workers.ts
=> #5228 [Manager] Create some helpful Observables

ohara-manager/client/src/store/epics/workspace/restartWorkspaceEpic.js
=> #5139 In any case can enter the setting page to use restart workspace

ohara-manager/client/src/api/__mocks__/fileApi.ts, ohara-manager/client/src/store/epics/__tests__/file/createFileEpic.test.js, ohara-manager/client/src/store/epics/broker/updateBrokerEpic.js, ohara-manager/client/src/store/epics/file/createFileEpic.js, ohara-manager/client/src/store/epics/worker/updateWorkerEpic.js, ohara-manager/client/src/store/epics/workspace/restartWorkspaceEpic.js, ohara-manager/client/src/store/epics/workspace/updateWorkspaceEpic.js, ohara-manager/client/src/store/epics/zookeeper/updateZookeeperEpic.js
=> #5258 [Manager]Support same name file upload to workspace

ohara-manager/client/cypress/support/customCommands.ts, ohara-manager/client/src/components/Workspace/CreateWorkspace/CreateWorkspace.js, ohara-manager/client/src/components/common/FSMStepper/Controller.js, ohara-manager/client/src/components/common/FSMStepper/LogViewer.js, ohara-manager/client/src/components/common/FSMStepper/Progress.js, ohara-manager/client/src/components/common/FSMStepper/Styles.js, ohara-manager/client/src/components/common/FSMStepper/const.js, ohara-manager/client/src/components/common/FSMStepper/index.js, ohara-manager/client/src/components/common/FSMStepper/stepperMachine.js, ohara-manager/client/src/components/common/FSMStepper/utils.js
=> #5346 [Manager] New log viewer for workspace creation

ohara-manager/client/cypress/it/appBar/appBar.test.ts, ohara-manager/client/src/api/apiInterface/workspaceInterface.ts, ohara-manager/client/src/components/Layout/AppBar.js, ohara-manager/client/src/components/Workspace/CreateWorkspace/CreateWorkspace.js, ohara-manager/client/src/components/Workspace/Settings/DangerZone/DeleteWorkspace.js, ohara-manager/client/src/components/Workspace/WorkspaceList.js, ohara-manager/client/src/hooks/createWorkspaceHooks.js, ohara-manager/client/src/hooks/workspaceHooks.js, ohara-manager/client/src/observables/workspaces.ts, ohara-manager/client/src/store/epics/__tests__/broker/createBrokerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/worker/createWorkerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/workspace/updateWorkspaceEpic.test.js, ohara-manager/client/src/store/epics/__tests__/zookeeper/createZookeeperEpic.test.js, ohara-manager/client/src/store/epics/broker/createBrokerEpic.js, ohara-manager/client/src/store/epics/worker/createWorkerEpic.js, ohara-manager/client/src/store/epics/workspace/updateWorkspaceEpic.js, ohara-manager/client/src/store/epics/zookeeper/createZookeeperEpic.js, ohara-manager/client/src/utils/workspace.ts
=> #5365 [Manager] Highlight the unstable workspace

ohara-manager/client/cypress/it/appBar/appBar.test.ts, ohara-manager/client/src/components/Layout/AppBar.js, ohara-manager/client/src/components/Workspace/WorkspaceList.js, ohara-manager/client/src/components/Workspace/WorkspaceListStyles.js, ohara-manager/client/src/store/epics/workspace/switchWorkspaceEpic.js, ohara-manager/client/src/store/selectors/workspaceSelector.js, ohara-manager/client/src/utils/workspace.ts
=> #5385 [Manager] Prevent users to use the unstable workspace

ohara-manager/client/cypress/it/appBar/appBar.test.ts, ohara-manager/client/src/api/__mocks__/brokerApi.ts, ohara-manager/client/src/api/__mocks__/zookeeperApi.ts, ohara-manager/client/src/observables/__tests__/brokers.test.js, ohara-manager/client/src/observables/__tests__/zookeepers.test.js, ohara-manager/client/src/observables/brokers.ts, ohara-manager/client/src/observables/utils.ts, ohara-manager/client/src/observables/workers.ts, ohara-manager/client/src/observables/zookeepers.ts, ohara-manager/client/src/store/epics/__tests__/broker/createBrokerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/broker/deleteBrokerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/broker/startBrokerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/broker/stopBrokerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/worker/startWorkerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/worker/stopWorkerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/zookeeper/createZookeeperEpic.test.js, ohara-manager/client/src/store/epics/__tests__/zookeeper/deleteZookeeperEpic.test.js, ohara-manager/client/src/store/epics/__tests__/zookeeper/startZookeeperEpic.test.js, ohara-manager/client/src/store/epics/__tests__/zookeeper/stopZookeeperEpic.test.js
=> #5396 [Manager] Message should be precise when docker image doesn't exist

ohara-manager/client/cypress/it/navigator/dangerZone.test.ts, ohara-manager/client/src/components/Workspace/Settings/DangerZone/RestartWorkspace.js
=> #5139 Restart workspace fail need highlight the unstable workspace

gradle.properties
=> #5427 Change branch versions from master to 0.11.x

docker/backend.yml, docker/build.yml, gradle.properties, ohara-manager/client/package.json, ohara-manager/package.json
=> #5429 Change 0.11.0-SNAPSHOT to 0.12.0-SNAPSHOT for master branch

ohara-manager/client/cypress/e2e/pipeline.test.ts, ohara-manager/client/cypress/it/paper/propertyDialog.test.ts, ohara-manager/client/src/components/common/Definitions/Tags.js
=> #5437 [Manager] The error of render tags was not handled properly

ohara-manager/client/src/components/Pipeline/PipelineHooks.js
=> #5461 [Manager] Property view metrics will not update data

ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/JDBCSourceTask.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorTimeRange.scala, ohara-it/src/test/scala/oharastream/ohara/it/connector/jdbc/BasicTestConnectorCollie.scala
=> #5455 fix flaky out of memory for the JDBC source task

ohara-it/src/main/scala/oharastream/ohara/it/stream/DumbStream.scala
=> #5485 Stream IT jar only contains one custom field

ohara-manager/client/src/store/epics/broker/createBrokerEpic.js, ohara-manager/client/src/store/epics/broker/deleteBrokerEpic.js, ohara-manager/client/src/store/epics/broker/startBrokerEpic.js, ohara-manager/client/src/store/epics/broker/stopBrokerEpic.js, ohara-manager/client/src/store/epics/file/deleteFileEpic.js, ohara-manager/client/src/store/epics/worker/createWorkerEpic.js, ohara-manager/client/src/store/epics/worker/deleteWorkerEpic.js, ohara-manager/client/src/store/epics/worker/startWorkerEpic.js, ohara-manager/client/src/store/epics/worker/stopWorkerEpic.js, ohara-manager/client/src/store/epics/workspace/updateWorkspaceEpic.js, ohara-manager/client/src/store/epics/zookeeper/createZookeeperEpic.js, ohara-manager/client/src/store/epics/zookeeper/deleteZookeeperEpic.js, ohara-manager/client/src/store/epics/zookeeper/startZookeeperEpic.js, ohara-manager/client/src/store/epics/zookeeper/stopZookeeperEpic.js
=> #5498 [Manager] Clean up unused epic

ohara-manager/client/src/api/__mocks__/connectorApi.ts, ohara-manager/client/src/api/apiInterface/clusterInterface.ts, ohara-manager/client/src/api/utils/apiUtils.ts, ohara-manager/client/src/hooks/connectorHooks.js, ohara-manager/client/src/observables/connectors.ts, ohara-manager/client/src/observables/utils.ts, ohara-manager/client/src/store/epics/__tests__/connector/createConnectorEpic.test.js, ohara-manager/client/src/store/epics/__tests__/connector/deleteConnectorEpic.test.js, ohara-manager/client/src/store/epics/__tests__/connector/fetchConnectorsEpic.test.js, ohara-manager/client/src/store/epics/__tests__/connector/startConnectorEpic.test.js, ohara-manager/client/src/store/epics/__tests__/connector/stopConnectorEpic.test.js, ohara-manager/client/src/store/epics/__tests__/connector/stopConnectorsEpic.test.js, ohara-manager/client/src/store/epics/__tests__/pipeline/deletePipelineEpic.test.js, ohara-manager/client/src/store/epics/connector/startConnectorEpic.js, ohara-manager/client/src/store/epics/connector/stopConnectorEpic.js
=> #5507 [Manager] Ensure Paper elements get the correct status from Connector API

ohara-manager/client/cypress/it/navigator/dangerZone.test.ts, ohara-manager/client/src/components/Layout/AppLayout.js, ohara-manager/client/src/components/Workspace/Settings/DangerZone/DeleteWorkspace.js, ohara-manager/client/src/components/Workspace/Settings/Settings.js, ohara-manager/client/src/store/reducers/ui/dialog.js
=> #5510 [Manager] Avoid directly closing the DeleteWorkspace dialog

ohara-manager/client/cypress/it/paper/elements.test.ts, ohara-manager/client/src/const.ts, ohara-manager/client/src/observables/__tests__/brokers.test.js, ohara-manager/client/src/observables/__tests__/topics.test.js, ohara-manager/client/src/observables/__tests__/workers.test.js, ohara-manager/client/src/observables/__tests__/zookeepers.test.js, ohara-manager/client/src/observables/brokers.ts, ohara-manager/client/src/observables/connectors.ts, ohara-manager/client/src/observables/shabondis.ts, ohara-manager/client/src/observables/streams.ts, ohara-manager/client/src/observables/topics.ts, ohara-manager/client/src/observables/workers.ts, ohara-manager/client/src/observables/zookeepers.ts, ohara-manager/client/src/store/epics/__tests__/broker/startBrokerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/broker/stopBrokerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/connector/startConnectorEpic.test.js, ohara-manager/client/src/store/epics/__tests__/connector/stopConnectorEpic.test.js, ohara-manager/client/src/store/epics/__tests__/shabondi/startShabondiEpic.test.js, ohara-manager/client/src/store/epics/__tests__/shabondi/stopShabondiEpic.test.js, ohara-manager/client/src/store/epics/__tests__/stream/startStreamEpic.test.js, ohara-manager/client/src/store/epics/__tests__/stream/stopStreamEpic.test.js, ohara-manager/client/src/store/epics/__tests__/worker/inspectWorkerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/worker/startWorkerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/worker/stopWorkerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/zookeeper/startZookeeperEpic.test.js, ohara-manager/client/src/store/epics/__tests__/zookeeper/stopZookeeperEpic.test.js, ohara-manager/client/src/store/epics/worker/inspectWorkerEpic.js
=> #5519 [Manager] Do not retry the START/STOP APIs for services

docker/backend.yml, docker/build.yml, gradle.properties, ohara-manager/client/package.json, ohara-manager/package.json
=> #5533 Change 0.11.0-SNAPSHOT to 0.11.0 for 0.11.x branch

ohara-manager/client/src/api/__mocks__/fileApi.ts, ohara-manager/client/src/api/__mocks__/inspectApi.ts, ohara-manager/client/src/api/__mocks__/nodeApi.ts, ohara-manager/client/src/api/__mocks__/pipelineApi.ts, ohara-manager/client/src/api/__mocks__/workspaceApi.ts, ohara-manager/client/src/store/epics/__tests__/app/initializeAppEpic.test.js, ohara-manager/client/src/store/epics/__tests__/broker/fetchBrokerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/devTool/fetchTopicDataEpic.test.js, ohara-manager/client/src/store/epics/__tests__/file/createFileEpic.test.js, ohara-manager/client/src/store/epics/__tests__/file/deleteFileEpic.test.js, ohara-manager/client/src/store/epics/__tests__/file/fetchFilesEpic.test.js, ohara-manager/client/src/store/epics/__tests__/nodeEpics.test.js, ohara-manager/client/src/store/epics/__tests__/pipeline/createPipelineEpic.test.js, ohara-manager/client/src/store/epics/__tests__/pipeline/deletePipelineEpic.test.js, ohara-manager/client/src/store/epics/__tests__/worker/inspectWorkerEpic.test.js, ohara-manager/client/src/store/epics/__tests__/workspace/createWorkspaceEpic.test.js, ohara-manager/client/src/store/epics/__tests__/zookeeper/fetchZookeeperEpic.test.js
=> #5415 [Manager] Unify the time delay of mock APIs

docker/backend.yml, docker/build.yml, gradle.properties, ohara-manager/client/package.json, ohara-manager/package.json
=> #5534 Change 0.11.0 to 0.11.1-SNAPSHOT for 0.11.x branch

docker/deps.dockerfile, gradle/wrapper/gradle-wrapper.properties
=> #5561 Upgrade gradle from 6.5.1 to 6.6

ohara-manager/client/src/api/__mocks__/volumeApi.ts, ohara-manager/client/src/api/apiInterface/volumeInterface.ts, ohara-manager/client/src/api/utils/apiUtils.ts, ohara-manager/client/src/api/volumeApi.ts, ohara-manager/client/src/hooks/index.js, ohara-manager/client/src/hooks/volumeHooks.js, ohara-manager/client/src/store/actions/index.js, ohara-manager/client/src/store/actions/volumeActions.js, ohara-manager/client/src/store/epics/__tests__/volume/createVolumeEpic.test.js, ohara-manager/client/src/store/epics/__tests__/volume/deleteVolumeEpic.test.js, ohara-manager/client/src/store/epics/__tests__/volume/fetchVolumeEpic.test.js, ohara-manager/client/src/store/epics/__tests__/volume/startVolumeEpic.test.js, ohara-manager/client/src/store/epics/__tests__/volume/stopVolumeEpic.test.js, ohara-manager/client/src/store/epics/__tests__/volume/updateVolumeEpic.test.js, ohara-manager/client/src/store/epics/index.js, ohara-manager/client/src/store/epics/volume/createVolumeEpic.js, ohara-manager/client/src/store/epics/volume/deleteVolumeEpic.js, ohara-manager/client/src/store/epics/volume/fetchVolumesEpic.js, ohara-manager/client/src/store/epics/volume/index.js, ohara-manager/client/src/store/epics/volume/startVolumeEpic.js, ohara-manager/client/src/store/epics/volume/stopVolumeEpic.js, ohara-manager/client/src/store/epics/volume/updateVolumeEpic.js, ohara-manager/client/src/store/reducers/entities/index.js, ohara-manager/client/src/store/reducers/entities/volumes.js, ohara-manager/client/src/store/reducers/ui/index.js, ohara-manager/client/src/store/reducers/ui/volume.js, ohara-manager/client/src/store/schema/index.js, ohara-manager/client/src/store/selectors/volumeSelector.js
=> #5551 Introduce volume api

README.md
=> #5584 Remove older document link for the README.md file

ohara-manager/client/cypress/it/appBar/createWorkspace.test.ts, ohara-manager/client/cypress/it/navigator/dangerZone.test.ts, ohara-manager/client/cypress/support/customCommands.ts, ohara-manager/client/src/components/Workspace/CreateWorkspace/CreateWorkspace.js, ohara-manager/client/src/components/Workspace/CreateWorkspace/CreateWorkspaceForm.js, ohara-manager/client/src/components/Workspace/CreateWorkspace/ReviewForm.js, ohara-manager/client/src/components/Workspace/CreateWorkspace/SetupVolumeForm.js, ohara-manager/client/src/components/Workspace/CreateWorkspace/validateVolumePath.js, ohara-manager/client/src/components/common/Form/ValidateInputField.js, ohara-manager/client/src/components/common/Form/index.js, ohara-manager/client/src/const.ts, ohara-manager/client/src/hooks/volumeHooks.js, ohara-manager/client/src/store/epics/__tests__/volume/createVolumeEpic.test.js, ohara-manager/client/src/store/epics/__tests__/volume/deleteVolumeEpic.test.js, ohara-manager/client/src/store/epics/__tests__/volume/startVolumeEpic.test.js, ohara-manager/client/src/store/epics/__tests__/volume/stopVolumeEpic.test.js, ohara-manager/client/src/store/epics/volume/createVolumeEpic.js, ohara-manager/client/src/store/epics/volume/deleteVolumeEpic.js, ohara-manager/client/src/store/epics/volume/index.js, ohara-manager/client/src/store/epics/volume/startVolumeEpic.js, ohara-manager/client/src/store/epics/volume/stopVolumeEpic.js, ohara-manager/client/src/store/epics/volume/validateVolumePath.js, ohara-manager/client/src/store/reducers/ui/volume.js, ohara-manager/client/src/store/selectors/volumeSelector.js, ohara-manager/client/src/utils/validate.js
=> #5551 [Manager] Introduce volume with quick create workspace

ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/JDBCSourceTask.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorExactlyOnce.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorRecovery.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorTimeRange.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTask.scala
=> #5434 Avoid using while loop to calculate time range

ohara-client/src/main/scala/oharastream/ohara/client/filesystem/ftp/FtpClient.scala, ohara-client/src/test/scala/oharastream/ohara/client/filesystem/ftp/TestFtpFileSystem.scala
=> #5587 exclude 426 error code when closing ftp inputstream

docker/backend.yml, docker/build.yml, gradle.properties, ohara-manager/client/package.json, ohara-manager/package.json
=> #5617 Change 0.11.1-SNAPSHOT to 0.11.1 for 0.11.x branch

docker/backend.yml, docker/build.yml, gradle.properties, ohara-manager/client/package.json, ohara-manager/package.json
=> #5619 Change 0.11.1 to 0.11.2-SNAPSHOT for 0.11.x branch

ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/JDBCSourceConnector.scala, ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/JDBCSourceConnectorConfig.scala, ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/package.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorConfig.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTask.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTaskOffset.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTaskRecovery.scala
=> #5434 Added increment setting to the JDBC source connector

ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/JDBCSourceTask.scala, ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/source/TimestampIncrementQueryHandler.scala, ohara-connector/src/test/resources/log4j.properties, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorExactlyOnce.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestTimestampIncrementQueryHandler.scala
=> #5434 Support Increment+timestamp qury for the exactly once

ohara-manager/client/cypress/it/navigator/dangerZone.test.ts, ohara-manager/client/src/components/Volume/VolumeCreateDialog.js, ohara-manager/client/src/components/Volume/VolumeEditDialog.js, ohara-manager/client/src/components/Volume/VolumeTable.js, ohara-manager/client/src/components/Volume/index.js, ohara-manager/client/src/components/Workspace/CreateWorkspace/CreateWorkspace.js, ohara-manager/client/src/components/Workspace/CreateWorkspace/CreateWorkspaceForm.js, ohara-manager/client/src/components/Workspace/Settings/DangerZone/RestartWorkspace.js, ohara-manager/client/src/components/Workspace/Settings/SettingsHooks.js, ohara-manager/client/src/components/Workspace/Settings/pages/BrokerVolumesPage.js, ohara-manager/client/src/components/Workspace/Settings/pages/ZookeeperVolumesPage.js, ohara-manager/client/src/components/common/Form/ArrayField.js, ohara-manager/client/src/components/common/Form/AutoComplete.js, ohara-manager/client/src/components/common/Form/ValidateInputFinalFormField.js, ohara-manager/client/src/const.ts, ohara-manager/client/src/hooks/volumeHooks.js, ohara-manager/client/src/hooks/workspaceHooks.js, ohara-manager/client/src/store/actions/volumeActions.js, ohara-manager/client/src/store/epics/__tests__/volume/updateVolumeEpic.test.js, ohara-manager/client/src/store/epics/volume/updateVolumeEpic.js, ohara-manager/client/src/store/epics/volume/validateVolumePath.js, ohara-manager/client/src/store/reducers/ui/volume.js, ohara-manager/client/src/store/selectors/volumeSelector.js, ohara-manager/package.json
=> #5551 Introduce volume with setting page

ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorExactlyOnce.scala
=> #5434 Modify unit test for the TestJDBCSourceConnectorExactlyOnce

ohara-connector/src/main/scala/oharastream/ohara/connector/jdbc/datatype/PostgresqlDataTypeConverter.scala, ohara-it/src/test/scala/oharastream/ohara/it/connector/jdbc/BasicTestConnectorCollie.scala, ohara-it/src/test/scala/oharastream/ohara/it/connector/jdbc/TestOracleJDBCSourceConnector.scala, ohara-it/src/test/scala/oharastream/ohara/it/connector/jdbc/TestOracleTimestampIncrementJDBCSourceConnector.scala, ohara-it/src/test/scala/oharastream/ohara/it/connector/jdbc/TestOracleTimestampJDBCSourceConnector.scala, ohara-it/src/test/scala/oharastream/ohara/it/connector/jdbc/TestPostgresqlJDBCSourceConnector.scala, ohara-it/src/test/scala/oharastream/ohara/it/connector/jdbc/TestPostgresqlTimestampIncrementJDBCSourceConnector.scala, ohara-it/src/test/scala/oharastream/ohara/it/connector/jdbc/TestPostgresqlTimestampJDBCSourceConnector.scala
=> #5434 Added jdbc source connector integration test for the increment+timestamp mode

ohara-connector/src/main/scala/oharastream/ohara/connector/perf/PerfSourceTask.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/perf/TestPerfSource.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/perf/TestPerfSourceTask.scala
=> #5656 Modify java data type for the PerfSourceTask result cell

ohara-manager/client/src/store/epics/volume/validateVolumePath.js
=> #5685 [Manager] Volumes used for verification should be deleted

ohara-manager/client/cypress/it/navigator/dangerZone.test.ts, ohara-manager/client/src/components/Node/NodeTable.js, ohara-manager/client/src/components/Topic/TopicTable.js, ohara-manager/client/src/components/Volume/VolumeTable.js
=> #5681 [Manager] Change the icon of create to be easier to understand

ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnector.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorDataType.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorExactlyOnce.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorRecovery.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceConnectorTimeRange.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTask.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTaskOffset.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestJDBCSourceTaskRecovery.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestMultipleJDBCSourceConnector.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestTimestampIncrementQueryHandler.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/jdbc/source/TestTimestampQueryHandler.scala
=> #5660 Make sure all tables crated by tests are cleanup

ohara-manager/client/.eslintrc.js
=> #5694 [Manager] Add more ESLint rules to TypeScript type components

ohara-manager/client/src/components/Volume/VolumeEditDialog.js, ohara-manager/client/src/components/Volume/VolumeTable.js
=> #5698 [Manager] Fix nodes rendering in volume table

ohara-agent/src/main/scala/oharastream/ohara/agent/k8s/K8SClient.scala
=> #5687 Refactor code style for the K8SClient object

ohara-manager/client/src/components/Workspace/CreateWorkspace/CreateWorkspaceForm.js, ohara-manager/client/src/components/Workspace/CreateWorkspace/ReviewForm.js, ohara-manager/client/src/components/Workspace/CreateWorkspace/SetupVolumeForm.js, ohara-manager/client/src/components/common/Form/Checkbox.js, ohara-manager/client/src/components/common/Form/ValidateInputField.js, ohara-manager/client/src/observables/__tests__/volumes.test.js, ohara-manager/client/src/observables/utils.ts, ohara-manager/client/src/observables/volumes.ts
=> #5700 [Manager] Fix some bugs about creating volumes

ohara-agent/src/main/scala/oharastream/ohara/agent/ServiceCollie.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/container/ContainerClient.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/container/ContainerVolume.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/docker/DockerClient.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/k8s/K8SClient.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/k8s/K8SJson.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/k8s/K8SServiceCollieImpl.scala, ohara-agent/src/test/scala/oharastream/ohara/agent/k8s/TestK8SClient.scala, ohara-configurator/src/main/scala/oharastream/ohara/configurator/fake/FakeServiceCollie.scala, ohara-it/src/test/scala/oharastream/ohara/it/collie/TestContainerClient.scala
=> #5693 Added hash code for the k8s volume name endwith

ohara-agent/src/main/scala/oharastream/ohara/agent/ServiceCollie.scala, ohara-it/src/test/scala/oharastream/ohara/it/ContainerPlatform.scala, ohara-it/src/test/scala/oharastream/ohara/it/collie/TestCollie.scala
=> #5717 Could not add volumes in quickstart of docker mode

ohara-manager/client/cypress/it/appBar/devTool.test.ts, ohara-manager/client/src/components/DevTool/Body/View/ViewLog.js, ohara-manager/client/src/components/common/LogViewer.tsx
=> #5745 [Manager] The latest log should be displayed first on devTool

ohara-configurator/src/test/scala/oharastream/ohara/configurator/TestConsoleSinkConnector.scala, ohara-connector/src/main/scala/oharastream/ohara/connector/console/ConsoleSink.scala, ohara-connector/src/main/scala/oharastream/ohara/connector/console/ConsoleSinkTask.scala, ohara-connector/src/main/scala/oharastream/ohara/connector/console/package.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/console/TestConsoleSettingDef.scala, ohara-connector/src/test/scala/oharastream/ohara/connector/console/TestConsoleSinkTask.scala
=> #5738 Add Schema field to consoleSink connector

ohara-agent/src/main/scala/oharastream/ohara/agent/ServiceCollie.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/container/ContainerClient.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/container/ContainerVolume.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/docker/DockerClient.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/k8s/K8SClient.scala, ohara-configurator/src/main/scala/oharastream/ohara/configurator/fake/FakeServiceCollie.scala, ohara-configurator/src/main/scala/oharastream/ohara/configurator/route/DataChecker.scala, ohara-it/src/test/scala/oharastream/ohara/it/collie/TestContainerClient.scala
=> #5744 Modify hash code of volume name from the ContainerClient to Collie

ohara-agent/src/main/scala/oharastream/ohara/agent/ServiceCollie.scala, ohara-it/src/test/scala/oharastream/ohara/it/collie/TestCollie.scala
=> #5798 Fix flakey can't create the volume 

ohara-configurator/src/main/scala/oharastream/ohara/configurator/route/package.scala, ohara-configurator/src/test/scala/oharastream/ohara/configurator/route/TestBrokerRoute.scala
=> #5810 Increment APIs should validate node name

ohara-agent/src/main/scala/oharastream/ohara/agent/Collie.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/ServiceCollie.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/container/ContainerVolume.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/docker/BasicCollieImpl.scala, ohara-agent/src/main/scala/oharastream/ohara/agent/k8s/K8SBasicCollieImpl.scala, ohara-configurator/src/main/scala/oharastream/ohara/configurator/route/VolumeRoute.scala, ohara-it/src/test/scala/oharastream/ohara/it/collie/TestCollie.scala
=> #5806 Fix container can't mount the volume
